In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_excel('Localizacao.xlsx')
df2=pd.read_excel('Vizinhos.xlsx', sheet_name='LB_Eurovision')
dflocal=pd.DataFrame(columns=['IDLocalizacao','Pais'])

In [3]:
df2.rename(columns = {'Name':'English Name'}, inplace = True)
df2.drop(columns=['Neighbour10', 'Neighbour9','Neighbour8', 'Neighbour7','Neighbour6', 'Neighbour5','Neighbour4', 'Neighbour3','Neighbour2','Neighbour1','Unnamed: 3', 'Unnamed: 14'])

      ID            English Name  NrNeighboursinEurope
0   30.0                 Albania                     4
1    3.0                 Andorra                     2
2   49.0                 Armenia                     4
3    5.0               Australia                     0
4   19.0                 Austria                     8
5   47.0              Azerbaijan                     5
6    NaN                 Belarus                     5
7    9.0                 Belgium                     4
8   26.0  Bosnia and Herzegovina                     3
9   33.0                Bulgaria                     4
10  25.0                 Croatia                     5
11  46.0                  Cyprus                     0
12  21.0                 Czechia                     4
13  22.0                 Denmark                     1
14  40.0                 Estonia                     2
15  44.0                 Finland                     3
16   4.0                  France                     6
17  41.0                 Georgia                     4
18  18.0                 Germany                     9
19  31.0                  Greece                     4
20   NaN                 Hungary                     7
21   6.0                 Iceland                     0
22   7.0                 Ireland                     1
23  48.0                  Israel                     0
24  17.0                   Italy                     6
25  29.0                  Kosovo                     4
26  39.0                  Latvia                     4
27  20.0           Liechtenstein                     2
28  38.0               Lithuania                     4
29  11.0              Luxembourg                     3
30  15.0                   Malta                     0
31  35.0                 Moldova                     2
32  14.0                  Monaco                     1
33  27.0              Montenegro                     5
34  50.0                 Morocco                     0
35  10.0             Netherlands                     2
36  32.0         North Macedonia                     5
37  42.0                  Norway                     3
38  36.0                  Poland                     7
39   1.0                Portugal                     1
40  34.0                 Romania                     5
41  37.0                  Russia                    10
42  16.0              San Marino                     1
43  28.0                  Serbia                     8
44  23.0                Slovakia                     6
45  24.0                Slovenia                     4
46   2.0                   Spain                     3
47  43.0                  Sweden                     2
48  12.0             Switzerland                     5
49  45.0                  Turkey                     5
50   8.0          United Kingdom                     1
51  13.0                 Vatican                     1
52   NaN                 Ukraine                     6
53   NaN   Serbia and Montenegro                     7
54   NaN              Yugoslavia                     7

In [4]:
print(df2)

      ID            English Name  NrNeighboursinEurope  \
0   30.0                 Albania                     4
1    3.0                 Andorra                     2
2   49.0                 Armenia                     4
3    5.0               Australia                     0
4   19.0                 Austria                     8
5   47.0              Azerbaijan                     5
6    NaN                 Belarus                     5
7    9.0                 Belgium                     4
8   26.0  Bosnia and Herzegovina                     3
9   33.0                Bulgaria                     4
10  25.0                 Croatia                     5
11  46.0                  Cyprus                     0
12  21.0                 Czechia                     4
13  22.0                 Denmark                     1
14  40.0                 Estonia                     2
15  44.0                 Finland                     3
16   4.0                  France                     6
17  41.0                 Georgia                     4
18  18.0                 Germany                     9
19  31.0                  Greece                     4
20   NaN                 Hungary                     7
21   6.0                 Iceland                     0
22   7.0                 Ireland                     1
23  48.0                  Israel                     0
24  17.0                   Italy                     6
25  29.0                  Kosovo                     4
26  39.0                  Latvia                     4
27  20.0           Liechtenstein                     2
28  38.0               Lithuania                     4
29  11.0              Luxembourg                     3
30  15.0                   Malta                     0
31  35.0                 Moldova                     2
32  14.0                  Monaco                     1
33  27.0              Montenegro                     5
34  50.0                 Morocco                     0
35  10.0             Netherlands                     2
36  32.0         North Macedonia                     5
37  42.0                  Norway                     3
38  36.0                  Poland                     7
39   1.0                Portugal                     1
40  34.0                 Romania                     5
41  37.0                  Russia                    10
42  16.0              San Marino                     1
43  28.0                  Serbia                     8
44  23.0                Slovakia                     6
45  24.0                Slovenia                     4
46   2.0                   Spain                     3
47  43.0                  Sweden                     2
48  12.0             Switzerland                     5
49  45.0                  Turkey                     5
50   8.0          United Kingdom                     1
51  13.0                 Vatican                     1
52   NaN                 Ukraine                     6
53   NaN   Serbia and Montenegro                     7
54   NaN              Yugoslavia                     7

                                           Unnamed: 3              Neighbour1  \
0      Montenegro Kosovo North Macedonia Greece                    Montenegro
1                                Spain France                           Spain
2                Azerbaijan Georgia Iran Turkey                    Azerbaijan
3                                                                         NaN
4   Germany Czechia Slovakia Hungary Slovenia Ital...                 Germany
5             Russia Georgia Armenia Iran Turkey                       Russia
6              Russia Latvia Lithuania Poland Ukraine                  Russia
7         France Luxembourg Netherlands Germany                        France
8                    Croatia Serbia Montenegro                        Croatia
9          Greece North Macedonia Turkey Serbia                        Greece
10  Slovenia Bosnia and Herzegovina Hungary Serbia...                Slovenia
11                                                                        NaN
12              Germany Poland Slovakia Austria                       Germany
13                                   Germany                          Germany
14                              Russia Latvia                          Russia
15                        Russia Norway Sweden                         Russia
16  Spain Andorra Monaco Italy Switzerland Luxembo...                   Spain
17             Russia Azerbaijan Armenia Turkey                        Russia
18  France Netherlands Belgium Luxembourg Switzerl...                  France
19      Albania North Macedonia Bulgaria Turkey                       Albania
20  Slovakia Ukraine Romania Serbia Croatia Sloven...                Slovakia
21                                                                        NaN
22                            United Kingdom                   United Kingdom
23                                                                        NaN
24  Vatican San Marino Switzerland France Austria ...                 Vatican
25    Serbia Montenegro North Macedonia Albania                        Serbia
26             Lithuania Belarus Estonia Russia                     Lithuania
27                        Austria Switzerland                         Austria
28                 Russia Poland Belarus Latvia                        Russia
29                      France Belgium Germany                         France
30                                                                        NaN
31                            Romenia Ukraine                         Romenia
32                                    France                           France
33  Bosnia and Herzegovina Serbia Kosovo Albania C...  Bosnia and Herzegovina
34                                                NaN                     NaN
35                            Belgium Germany                         Belgium
36         Albania Greece Bulgaria Kosovo Serbia                      Albania
37                       Sweden Finland Russia                         Sweden
38  Russia Lithuania Belarus Ukraine Slovakia Czec...                  Russia
39                                     Spain                            Spain
40       Bulgaria Serbia Moldova Ukraine Hungary                     Bulgaria
41  Poland Lithuania Estonia Latvia Belarus Ukrain...                  Poland
42                                     Italy                            Italy
43  Croatia Hungary Romania Bulgaria North Macedon...                 Croatia
44  Czechia Poland Ukraine Hungary Austria Germany...                 Czechia
45                Austria Hungary Croatia Italy                       Austria
46                     Portugal Andorra France                       Portugal
47                             Norway Finland                          Norway
48    France Germany Austria Italy Liechtenstein                       France
49    Georgia Armenia Bulgaria Greece Azerbaijan                      Georgia
50                                   Ireland                          Ireland
51                                     Italy                            Italy
52  Russia Moldova Romania Hungary Slovakia Poland...                  Russia
53  Hungary Romania Bulgaria North Macedonia Croat...                 Hungary
54  Italy Albania Greece Bulgaria Romania Czechia ...                   Italy

                Neighbour2       Neighbour3       Neighbour4       Neighbour5  \
0                   Kosovo  North Macedonia           Greece              NaN
1                   France              NaN              NaN              NaN
2                  Georgia             Iran           Turkey              NaN
3                      NaN              NaN              NaN              NaN
4                  Czechia         Slovakia          Hungary         Slovenia
5                  Georgia          Armenia             Iran           Turkey
6                   Latvia        Lithuania           Poland          Ukraine
7               Luxembourg      Netherlands          Germany              NaN
8                   Serbia       Montenegro              NaN              NaN
9          North Macedonia           Turkey           Serbia              NaN
10  Bosnia and Herzegovina          Hungary           Serbia       Montenegro
11                     NaN              NaN              NaN              NaN
12                  Poland         Slovakia          Austria              NaN
13                     NaN              NaN              NaN              NaN
14                  Latvia              NaN              NaN              NaN
15                  Norway           Sweden              NaN              NaN
16                 Andorra           Monaco            Italy      Switzerland
17              Azerbaijan          Armenia           Turkey              NaN
18             Netherlands          Belgium       Luxembourg      Switzerland
19         North Macedonia         Bulgaria           Turkey              NaN
20                 Ukraine          Romania           Serbia          Croatia
21                     NaN              NaN              NaN              NaN
22                     NaN              NaN              NaN              NaN
23                     NaN              NaN              NaN              NaN
24              San Marino      Switzerland           France          Austria
25              Montenegro  North Macedonia          Albania              NaN
26                 Belarus          Estonia           Russia              NaN
27             Switzerland              NaN              NaN              NaN
28                  Poland          Belarus           Latvia              NaN
29                 Belgium          Germany              NaN              NaN
30                     NaN              NaN              NaN              NaN
31                 Ukraine              NaN              NaN              NaN
32                     NaN              NaN              NaN              NaN
33                  Serbia           Kosovo          Albania          Croatia
34                     NaN              NaN              NaN              NaN
35                 Germany              NaN              NaN              NaN
36                  Greece         Bulgaria           Kosovo           Serbia
37                 Finland           Russia              NaN              NaN
38               Lithuania          Belarus          Ukraine         Slovakia
39                     NaN              NaN              NaN              NaN
40                  Serbia          Moldova          Ukraine          Hungary
41               Lithuania          Estonia           Latvia          Belarus
42                     NaN              NaN              NaN              NaN
43                 Hungary          Romania         Bulgaria  North Macedonia
44                  Poland          Ukraine          Hungary          Austria
45                 Hungary          Croatia            Italy              NaN
46                 Andorra           France              NaN              NaN
47                 Finland              NaN              NaN              NaN
48                 Germany          Austria            Italy    Liechtenstein
49                 Armenia         Bulgaria           Greece       Azerbaijan
50                     NaN              NaN              NaN              NaN
51                     NaN              NaN              NaN              NaN
52                 Moldova          Romania          Hungary         Slovakia
53                 Romania         Bulgaria  North Macedonia          Croatia
54                 Albania           Greece         Bulgaria          Romania

                Neighbour6   Neighbour7              Neighbour8 Neighbour9  \
0                      NaN          NaN                     NaN        NaN
1                      NaN          NaN                     NaN        NaN
2                      NaN          NaN                     NaN        NaN
3                      NaN          NaN                     NaN        NaN
4                    Italy  Switzerland           Liechtenstein        NaN
5                      NaN          NaN                     NaN        NaN
6                      NaN          NaN                     NaN        NaN
7                      NaN          NaN                     NaN        NaN
8                      NaN          NaN                     NaN        NaN
9                      NaN          NaN                     NaN        NaN
10                     NaN          NaN                     NaN        NaN
11                     NaN          NaN                     NaN        NaN
12                     NaN          NaN                     NaN        NaN
13                     NaN          NaN                     NaN        NaN
14                     NaN          NaN                     NaN        NaN
15                     NaN          NaN                     NaN        NaN
16              Luxembourg          NaN                     NaN        NaN
17                     NaN          NaN                     NaN        NaN
18                 Austria      Czechia                  Poland    Denmark
19                     NaN          NaN                     NaN        NaN
20                Slovenia      Austria                     NaN        NaN
21                     NaN          NaN                     NaN        NaN
22                     NaN          NaN                     NaN        NaN
23                     NaN          NaN                     NaN        NaN
24                Slovenia          NaN                     NaN        NaN
25                     NaN          NaN                     NaN        NaN
26                     NaN          NaN                     NaN        NaN
27                     NaN          NaN                     NaN        NaN
28                     NaN          NaN                     NaN        NaN
29                     NaN          NaN                     NaN        NaN
30                     NaN          NaN                     NaN        NaN
31                     NaN          NaN                     NaN        NaN
32                     NaN          NaN                     NaN        NaN
33                     NaN          NaN                     NaN        NaN
34                     NaN          NaN                     NaN        NaN
35                     NaN          NaN                     NaN        NaN
36                     NaN          NaN                     NaN        NaN
37                     NaN          NaN                     NaN        NaN
38                 Czechia      Germany                     NaN        NaN
39                     NaN          NaN                     NaN        NaN
40                     NaN          NaN                     NaN        NaN
41                 Ukraine      Georgia              Azerbaijan    Finland
42                     NaN          NaN                     NaN        NaN
43                  Kosovo   Montenegro  Bosnia and Herzegovina        NaN
44                 Germany          NaN                     NaN        NaN
45                     NaN          NaN                     NaN        NaN
46                     NaN          NaN                     NaN        NaN
47                     NaN          NaN                     NaN        NaN
48                     NaN          NaN                     NaN        NaN
49                     NaN          NaN                     NaN        NaN
50                     NaN          NaN                     NaN        NaN
51                     NaN          NaN                     NaN        NaN
52                  Poland      Belarus                     NaN        NaN
53  Bosnia and Herzegovina      Albania                     NaN        NaN
54                 Czechia      Hungary                     NaN        NaN

   Neighbour10  Unnamed: 14
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
5          NaN          NaN
6          NaN          NaN
7          NaN          NaN
8          NaN          NaN
9          NaN          NaN
10         NaN          NaN
11         NaN          NaN
12         NaN          NaN
13         NaN          NaN
14         NaN          NaN
15         NaN          NaN
16         NaN          NaN
17         NaN          NaN
18         NaN          NaN
19         NaN          NaN
20         NaN          NaN
21         NaN          NaN
22         NaN          NaN
23         NaN          NaN
24         NaN          NaN
25         NaN          NaN
26         NaN          NaN
27         NaN          NaN
28         NaN          NaN
29         NaN          NaN
30         NaN          NaN
31         NaN          NaN
32         NaN          NaN
33         NaN          NaN
34         NaN          NaN
35         NaN          NaN
36         NaN          NaN
37         NaN          NaN
38         NaN          NaN
39         NaN          NaN
40         NaN          NaN
41      Norway          NaN
42         NaN          NaN
43         NaN          NaN
44         NaN          NaN
45         NaN          NaN
46         NaN          NaN
47         NaN          NaN
48         NaN          NaN
49         NaN          NaN
50         NaN          NaN
51         NaN          NaN
52         NaN          NaN
53         NaN          NaN
54         NaN          NaN

In [5]:
result = pd.merge(df1, df2, on=["English Name"])

In [6]:
dflocal['Pais']=result['English Name']

In [7]:
dflocal['Regiao']=result['Region of the territory']
dflocal['Continente']=result['Continent of the territory']

In [8]:
dflocal['IDLocalizacao']=dflocal.index+1

In [9]:
dflocal['NumeroDeVizinhos']=result['NrNeighboursinEurope']

In [10]:
print(dflocal)

    IDLocalizacao                    Pais                     Regiao  \
0               1                 Albania            Southern Europe
1               2                 Andorra            Southern Europe
2               3                 Armenia               Western Asia
3               4               Australia  Australia and New Zealand
4               5                 Austria             Western Europe
5               6              Azerbaijan               Western Asia
6               7                 Belarus             Eastern Europe
7               8                 Belgium             Western Europe
8               9  Bosnia and Herzegovina            Southern Europe
9              10                Bulgaria             Eastern Europe
10             11                 Croatia            Southern Europe
11             12                  Cyprus               Western Asia
12             13                 Czechia             Eastern Europe
13             14                 Denmark            Northern Europe
14             15                 Estonia            Northern Europe
15             16                 Finland            Northern Europe
16             17                  France             Western Europe
17             18                 Georgia               Western Asia
18             19                 Germany             Western Europe
19             20                  Greece            Southern Europe
20             21                 Hungary             Eastern Europe
21             22                 Iceland            Northern Europe
22             23                 Ireland            Northern Europe
23             24                  Israel               Western Asia
24             25                   Italy            Southern Europe
25             26                  Latvia            Northern Europe
26             27               Lithuania            Northern Europe
27             28              Luxembourg             Western Europe
28             29                   Malta            Southern Europe
29             30                 Moldova             Eastern Europe
30             31                  Monaco             Western Europe
31             32              Montenegro            Southern Europe
32             33                 Morocco            Northern Africa
33             34         North Macedonia            Southern Europe
34             35             Netherlands             Western Europe
35             36                  Norway            Northern Europe
36             37                  Poland             Eastern Europe
37             38                Portugal            Southern Europe
38             39                 Romania             Eastern Europe
39             40                  Russia             Eastern Europe
40             41              San Marino            Southern Europe
41             42                  Serbia            Southern Europe
42             43                Slovakia             Eastern Europe
43             44                Slovenia            Southern Europe
44             45                   Spain            Southern Europe
45             46                  Sweden            Northern Europe
46             47             Switzerland             Western Europe
47             48                  Turkey               Western Asia
48             49          United Kingdom            Northern Europe
49             50                 Ukraine             Eastern Europe
50             51   Serbia and Montenegro            Southern Europe
51             52              Yugoslavia            Southern Europe

   Continente  NumeroDeVizinhos
0      Europe                 4
1      Europe                 2
2        Asia                 4
3     Oceania                 0
4      Europe                 8
5        Asia                 5
6      Europe                 5
7      Europe                 4
8      Europe                 3
9      Europe                 4
10     Europe                 5
11       Asia                 0
12     Europe                 4
13     Europe                 1
14     Europe                 2
15     Europe                 3
16     Europe                 6
17       Asia                 4
18     Europe                 9
19     Europe                 4
20     Europe                 7
21     Europe                 0
22     Europe                 1
23       Asia                 0
24     Europe                 6
25     Europe                 4
26     Europe                 4
27     Europe                 3
28     Europe                 0
29     Europe                 2
30     Europe                 1
31     Europe                 5
32     Africa                 0
33     Europe                 5
34     Europe                 2
35     Europe                 3
36     Europe                 7
37     Europe                 1
38     Europe                 5
39     Europe                10
40     Europe                 1
41     Europe                 8
42     Europe                 6
43     Europe                 4
44     Europe                 3
45     Europe                 2
46     Europe                 5
47       Asia                 5
48     Europe                 1
49     Europe                 6
50     Europe                 7
51     Europe                 7

In [11]:
dflocal.to_csv("DimLocalizacao.csv", index=False)